### ISSUE TITLE
Wrong `Time without finds` stat?

### ISSUE THREAD

**Issue by wizche** [0xricksanchez/AFL_Runner#47]
I see very big `Time without finds` , e.g. min value of > 4000 secs whereas if I loop across tmux instances I see `last new find` way smaller (e.g. 5 minutes). Is the calculation based on the current timestamp of the host? 
For example I see in `fuzzer_stats` of one instance:
```
last_find         : 1730983297
```
And my host timestamp is:
```
$ date '+%s'
1730983638
```
Which would mean in `1730983638-1730983297=341s` which is what I see in the AFL screen under `last new find`. 
My host time is not synchronized or anything but I guess it shouldnt affect the calculation since all instances will use the same time.

**Comment by 0xricksanchez** [comment]
If I recall correctly, the `time without finds` and calculation for the "elapsed time since last finds` were a little annoying in the current implementation.

AFLR uses the AFL++ stats file to get the last written stats to display in the UI, but at the same time maintains an internal timer/counter to display "live stats/tickers" as the AFL++ stats file is only written sporadically.

Regarding your issue: Host time synchronization should not matter. It should always the local time and display stats appropriately...
